"""Add genres column to artists table

Revision ID: 1f580ea03a8f
Revises: 3496945b3899
Create Date: 2023-12-08 00:20:10.621161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f580ea03a8f'
down_revision = '3496945b3899'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres', sa.String(length=120), nullable=True, server_default='default_value'))
        batch_op.drop_column('facebook_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facebook_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('genres')

    # ### end Alembic commands ###
