"""Add genres column to artists table

Revision ID: 3496945b3899
Revises: a153d5ea69a5
Create Date: 2023-12-08 00:15:04.933403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3496945b3899'
down_revision = 'a153d5ea69a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres', sa.String(length=120), nullable=True, server_default=''))
        batch_op.drop_column('facebook_link')
    # ### end Alembic commands ###




def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facebook_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('genres')

    # ### end Alembic commands ###
