"""Description of the changes

Revision ID: 9fc5e09b9d3c
Revises: 4e9c0139698c
Create Date: 2023-08-09 02:08:02.017251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc5e09b9d3c'
down_revision = '4e9c0139698c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=120), nullable=False))

    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.drop_column('city')

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_column('city')

    # ### end Alembic commands ###
