"""empty message

Revision ID: a17df519b585
Revises: 1ed2be378efa
Create Date: 2023-07-25 02:44:13.847048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a17df519b585'
down_revision = '1ed2be378efa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.drop_column('city_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
