"""Add facebook_link column to Artist model

Revision ID: bd1a462ffb95
Revises: 1f580ea03a8f
Create Date: 2023-12-08 02:50:47.744365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd1a462ffb95'
down_revision = '1f580ea03a8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_genres',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.PrimaryKeyConstraint('artist_id', 'genre_id')
    )
    op.drop_table('artist_genre')
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facebook_link', sa.String(length=120), nullable=True))
        batch_op.drop_column('genres')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres', sa.VARCHAR(length=120), server_default=sa.text("'default_value'::character varying"), autoincrement=False, nullable=True))
        batch_op.drop_column('facebook_link')

    op.create_table('artist_genre',
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name='artist_genre_artist_id_fkey'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name='artist_genre_genre_id_fkey'),
    sa.PrimaryKeyConstraint('artist_id', 'genre_id', name='artist_genre_pkey')
    )
    op.drop_table('artist_genres')
    # ### end Alembic commands ###
